import { ArrowUpRight, DatabaseZap } from 'lucide-react';
import { useAppStore } from '../store';
import { sourcesFor } from '../services/data';
import type { FieldSource, Project, Signal } from '../types/domain';
export function StatusBadge({s,label}:{s:Signal|string;label?:string}){const cls=s==='green'||label?.includes('完成')||label?.includes('正常')?'green':s==='red'||label?.includes('逾期')?'red':s==='gray'||label?.includes('无法')?'gray':'yellow';return <span className={`badge ${cls}`}>{label||({green:'绿色 正常',yellow:'黄色 关注',red:'红色 异常',gray:'灰色 待判断'} as any)[s]||s}</span>}
export function Card({title,value,desc,onClick}:{title:string;value:string|number;desc?:string;onClick?:()=>void}){return <div className={`card ${onClick?'click pulse':''}`} onClick={onClick}><div className="muted">{title}</div><div className="metric">{value}</div>{desc&&<div className="muted">{desc}</div>}{onClick&&<span className="badge blue" style={{marginTop:10}}>查看详情 <ArrowUpRight size={12}/></span>}</div>}
export function SourceButton({project,field}:{project:Project;field?:string}){const open=useAppStore(s=>s.openSource);const src=sourcesFor(project.id,field)[0]||sourcesFor(project.id)[0];return <button className="btn" onClick={()=>open(src)}><DatabaseZap size={14}/> 查看来源</button>}
export function VerificationDrawer(){const src=useAppStore(s=>s.source);const open=useAppStore(s=>s.openSource);if(!src)return null;return <><div className="overlay" onClick={()=>open(undefined)}/><div className="drawer"><div className="section-title"><h2>字段级核验与来源追溯</h2><button className="btn" onClick={()=>open(undefined)}>关闭</button></div><KV k="字段名称" v={src.fieldName}/><KV k="当前采用值" v={String(src.value)}/><KV k="来源文件" v={src.documentTitle}/><KV k="来源类型" v={src.sourceType}/><KV k="材料日期" v={src.materialDate}/><KV k="私域/外部" v={src.visibility==='private'?'私域材料':'外部材料'}/><KV k="位置" v={src.location||'章节/表格位置见材料索引'}/><KV k="信息类型" v={src.evidenceType==='explicit'?'明确事实':'AI推断'}/><KV k="置信度" v={`${Math.round(src.confidence*100)}%`}/><KV k="是否冲突" v={src.hasConflict?'存在冲突':'无冲突'}/><KV k="冲突来源" v={src.conflictSources||'无'}/><KV k="是否过期" v={src.isOutdated?'可能过期':'未过期'}/><KV k="人工确认" v={src.requiresConfirmation?'需要人工确认':'暂不需要'}/><div className="card"><b>原文摘录</b><p>{src.excerpt}</p></div><div className="card"><b>采用原因</b><p>{src.adoptionReason}</p><p className="muted">来源优先级：正式协议 → 审计/财务 → 工商 → 董事会/股东会 → 交割文件 → GP季报 → 企业季报 → 邮件/会议纪要 → BP → 外部公开材料 → 口头记录。</p></div></div></>}
function KV({k,v}:{k:string;v:string}){return <div className="kv"><b>{k}</b><span>{v}</span></div>}
export function ProjectMini({p}:{p:Project}){return <div><b>{p.shortName}</b><div className="muted">{p.industry} · {p.financingStage}</div></div>}